# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-19 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
